[package]
name        = "xtask"
description = "Repo automation for wsp. Not shipped."
publish     = false
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
tempfile = { workspace = true }
wsp-core = { path = "../wsp-core" }
terminal_size = { workspace = true }
unicode-width = { workspace = true }
vt100 = "0.16.2"
