use std::fmt;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::workspace::Metadata;

use super::LanguageIntegration;

const DEFAULT_GO_VERSION: GoVersion = GoVersion {
    major: 1,
    minor: 21,
    patch: None,
};

pub const GO_WORK_HEADER: &str = "// Code generated by wsp. DO NOT EDIT.";

pub struct GoIntegration;

impl LanguageIntegration for GoIntegration {
    fn name(&self) -> &str {
        "go"
    }

    fn detect(&self, ws_dir: &Path, metadata: &Metadata) -> bool {
        repo_dirs(ws_dir, metadata)
            .iter()
            .any(|(name, path)| !find_go_modules(path, name).is_empty())
    }

    fn apply(&self, ws_dir: &Path, metadata: &Metadata) -> Result<()> {
        let dirs = repo_dirs(ws_dir, metadata);
        let mut entries: Vec<(String, GoVersion)> = Vec::new();

        for (name, path) in &dirs {
            for mod_rel in find_go_modules(path, name) {
                let go_mod = ws_dir.join(&mod_rel).join("go.mod");
                let content = fs::read_to_string(&go_mod)
                    .with_context(|| format!("reading {}", go_mod.display()))?;
                let version = parse_go_version(&content).unwrap_or(DEFAULT_GO_VERSION);
                entries.push((mod_rel, version));
            }
        }

        if entries.is_empty() {
            return Ok(());
        }

        let max_version = entries
            .iter()
            .map(|(_, v)| v)
            .max()
            .cloned()
            .unwrap_or(DEFAULT_GO_VERSION);

        let mut names: Vec<&str> = entries.iter().map(|(n, _)| n.as_str()).collect();
        names.sort();

        let mut out = String::new();
        out.push_str(GO_WORK_HEADER);
        out.push('\n');
        out.push_str(&format!("go {}\n", max_version));
        out.push('\n');
        out.push_str("use (\n");
        for name in &names {
            out.push_str(&format!("\t./{}\n", name));
        }
        out.push_str(")\n");

        let tmp_path = ws_dir.join(".go.work.tmp");
        let final_path = ws_dir.join("go.work");
        fs::write(&tmp_path, out).with_context(|| format!("writing {}", tmp_path.display()))?;
        fs::rename(&tmp_path, &final_path).with_context(|| {
            format!(
                "renaming {} to {}",
                tmp_path.display(),
                final_path.display()
            )
        })?;
        Ok(())
    }
}

/// Returns (dir_name, repo_path) for all repos in the workspace.
fn repo_dirs(ws_dir: &Path, metadata: &Metadata) -> Vec<(String, PathBuf)> {
    let mut result = Vec::new();
    for identity in metadata.repos.keys() {
        if let Ok(dn) = metadata.dir_name(identity) {
            if dn.contains("..") || dn.starts_with('/') {
                continue;
            }
            let path = ws_dir.join(&dn);
            result.push((dn, path));
        }
    }
    result
}

/// Directories to skip when walking for go.mod files.
const SKIP_DIRS: &[&str] = &[".git", "vendor", "testdata", "node_modules"];

/// Recursively finds all `go.mod` files under `root`.
/// Returns workspace-relative paths (e.g. `repo-name/services/api`).
fn find_go_modules(root: &Path, repo_name: &str) -> Vec<String> {
    let mut results = Vec::new();
    walk_for_go_mod(root, repo_name, &mut results);
    results
}

fn walk_for_go_mod(dir: &Path, rel_path: &str, results: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };

    let is_regular_file = dir
        .join("go.mod")
        .symlink_metadata()
        .map(|m| m.file_type().is_file())
        .unwrap_or(false);
    if is_regular_file {
        results.push(rel_path.to_string());
    }

    let mut subdirs: Vec<_> = entries
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|ft| ft.is_dir()).unwrap_or(false))
        .filter(|e| {
            let name = e.file_name();
            let name = name.to_string_lossy();
            !name.starts_with('.') && !SKIP_DIRS.contains(&name.as_ref())
        })
        .collect();
    subdirs.sort_by_key(|e| e.file_name());

    for entry in subdirs {
        let child_rel = format!("{}/{}", rel_path, entry.file_name().to_string_lossy());
        walk_for_go_mod(&entry.path(), &child_rel, results);
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct GoVersion {
    pub major: u32,
    pub minor: u32,
    pub patch: Option<u32>,
}

impl Ord for GoVersion {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.major
            .cmp(&other.major)
            .then(self.minor.cmp(&other.minor))
            .then(self.patch.unwrap_or(0).cmp(&other.patch.unwrap_or(0)))
    }
}

impl PartialOrd for GoVersion {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl fmt::Display for GoVersion {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.patch {
            Some(p) => write!(f, "{}.{}.{}", self.major, self.minor, p),
            None => write!(f, "{}.{}", self.major, self.minor),
        }
    }
}

/// Parses the `go X.Y` or `go X.Y.Z` directive from go.mod content.
pub fn parse_go_version(content: &str) -> Option<GoVersion> {
    for line in content.lines() {
        let line = line.trim();
        if let Some(rest) = line.strip_prefix("go ") {
            let rest = rest.trim();
            let parts: Vec<&str> = rest.split('.').collect();
            if parts.len() >= 2
                && let (Ok(major), Ok(minor)) = (parts[0].parse(), parts[1].parse())
            {
                let patch = if parts.len() >= 3 {
                    parts[2].parse().ok()
                } else {
                    None
                };
                return Some(GoVersion {
                    major,
                    minor,
                    patch,
                });
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    use chrono::Utc;

    use crate::workspace::{Metadata, WorkspaceRepoRef};

    #[test]
    fn test_parse_go_version() {
        let cases = vec![
            (
                "standard",
                "module example.com/foo\n\ngo 1.21\n",
                Some(GoVersion {
                    major: 1,
                    minor: 21,
                    patch: None,
                }),
            ),
            (
                "with patch",
                "module example.com/foo\n\ngo 1.23.2\n",
                Some(GoVersion {
                    major: 1,
                    minor: 23,
                    patch: Some(2),
                }),
            ),
            ("missing", "module example.com/foo\n", None),
            ("empty", "", None),
            (
                "with toolchain",
                "module example.com/foo\n\ngo 1.22\n\ntoolchain go1.22.5\n",
                Some(GoVersion {
                    major: 1,
                    minor: 22,
                    patch: None,
                }),
            ),
            (
                "go 2.0",
                "module example.com/foo\n\ngo 2.0\n",
                Some(GoVersion {
                    major: 2,
                    minor: 0,
                    patch: None,
                }),
            ),
        ];
        for (name, input, want) in cases {
            let got = parse_go_version(input);
            assert_eq!(got, want, "{}", name);
        }
    }

    #[test]
    fn test_go_version_ordering() {
        let cases = vec![
            (
                "1.21 < 1.22",
                GoVersion {
                    major: 1,
                    minor: 21,
                    patch: None,
                },
                GoVersion {
                    major: 1,
                    minor: 22,
                    patch: None,
                },
                std::cmp::Ordering::Less,
            ),
            (
                "1.23 > 1.22",
                GoVersion {
                    major: 1,
                    minor: 23,
                    patch: None,
                },
                GoVersion {
                    major: 1,
                    minor: 22,
                    patch: None,
                },
                std::cmp::Ordering::Greater,
            ),
            (
                "1.21 == 1.21",
                GoVersion {
                    major: 1,
                    minor: 21,
                    patch: None,
                },
                GoVersion {
                    major: 1,
                    minor: 21,
                    patch: None,
                },
                std::cmp::Ordering::Equal,
            ),
            (
                "2.0 > 1.99",
                GoVersion {
                    major: 2,
                    minor: 0,
                    patch: None,
                },
                GoVersion {
                    major: 1,
                    minor: 99,
                    patch: None,
                },
                std::cmp::Ordering::Greater,
            ),
            (
                "1.25 < 1.25.7 (None patch treated as 0)",
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: None,
                },
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: Some(7),
                },
                std::cmp::Ordering::Less,
            ),
            (
                "1.25.7 == 1.25.7",
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: Some(7),
                },
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: Some(7),
                },
                std::cmp::Ordering::Equal,
            ),
            (
                "1.25.3 < 1.25.7",
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: Some(3),
                },
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: Some(7),
                },
                std::cmp::Ordering::Less,
            ),
        ];
        for (name, a, b, want) in cases {
            assert_eq!(a.cmp(&b), want, "{}", name);
        }
    }

    #[test]
    fn test_go_version_display() {
        let cases = vec![
            (
                "major.minor only",
                GoVersion {
                    major: 1,
                    minor: 23,
                    patch: None,
                },
                "1.23",
            ),
            (
                "with patch",
                GoVersion {
                    major: 1,
                    minor: 25,
                    patch: Some(7),
                },
                "1.25.7",
            ),
            (
                "patch zero",
                GoVersion {
                    major: 1,
                    minor: 22,
                    patch: Some(0),
                },
                "1.22.0",
            ),
        ];
        for (name, v, want) in cases {
            assert_eq!(v.to_string(), want, "{}", name);
        }
    }

    fn make_metadata(repos: &[&str]) -> Metadata {
        let mut map = BTreeMap::new();
        for id in repos {
            map.insert(id.to_string(), None);
        }
        Metadata {
            version: 0,
            name: "test".into(),
            branch: "test".into(),
            repos: map,
            created: Utc::now(),
            description: None,
            last_used: None,
            created_from: None,
            dirs: BTreeMap::new(),
            config: None,
        }
    }

    fn make_metadata_with_refs(repos: &[(&str, Option<&str>)]) -> Metadata {
        let mut map: BTreeMap<String, Option<WorkspaceRepoRef>> = BTreeMap::new();
        for (id, r) in repos {
            match r {
                None => {
                    map.insert(id.to_string(), None);
                }
                Some(ref_str) => {
                    map.insert(
                        id.to_string(),
                        Some(WorkspaceRepoRef {
                            r#ref: ref_str.to_string(),
                            url: None,
                        }),
                    );
                }
            }
        }
        Metadata {
            version: 0,
            name: "test".into(),
            branch: "test".into(),
            repos: map,
            created: Utc::now(),
            description: None,
            last_used: None,
            created_from: None,
            dirs: BTreeMap::new(),
            config: None,
        }
    }

    #[test]
    fn test_detect_with_go_mod() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let repo_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&repo_dir).unwrap();
        fs::write(
            repo_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.21\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway"]);
        let integration = GoIntegration;

        assert!(integration.detect(ws_dir, &meta));
    }

    #[test]
    fn test_detect_without_go_mod() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let repo_dir = ws_dir.join("frontend");
        fs::create_dir_all(&repo_dir).unwrap();
        fs::write(repo_dir.join("package.json"), "{}").unwrap();

        let meta = make_metadata(&["github.com/acme/frontend"]);
        let integration = GoIntegration;

        assert!(!integration.detect(ws_dir, &meta));
    }

    #[test]
    fn test_detect_mixed_repos() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        // One Go repo
        let go_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&go_dir).unwrap();
        fs::write(
            go_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.21\n",
        )
        .unwrap();

        // One non-Go repo
        let js_dir = ws_dir.join("frontend");
        fs::create_dir_all(&js_dir).unwrap();
        fs::write(js_dir.join("package.json"), "{}").unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway", "github.com/acme/frontend"]);
        let integration = GoIntegration;

        assert!(integration.detect(ws_dir, &meta));
    }

    #[test]
    fn test_apply_single_repo() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let repo_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&repo_dir).unwrap();
        fs::write(
            repo_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.22\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert_eq!(
            content,
            "// Code generated by wsp. DO NOT EDIT.\ngo 1.22\n\nuse (\n\t./api-gateway\n)\n"
        );
    }

    #[test]
    fn test_apply_multiple_repos_highest_version() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let api_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&api_dir).unwrap();
        fs::write(
            api_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.21\n",
        )
        .unwrap();

        let proto_dir = ws_dir.join("proto");
        fs::create_dir_all(&proto_dir).unwrap();
        fs::write(
            proto_dir.join("go.mod"),
            "module example.com/proto\n\ngo 1.23\n",
        )
        .unwrap();

        let user_dir = ws_dir.join("user-service");
        fs::create_dir_all(&user_dir).unwrap();
        fs::write(
            user_dir.join("go.mod"),
            "module example.com/user-service\n\ngo 1.22\n",
        )
        .unwrap();

        let meta = make_metadata(&[
            "github.com/acme/api-gateway",
            "github.com/acme/proto",
            "github.com/acme/user-service",
        ]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert_eq!(
            content,
            "// Code generated by wsp. DO NOT EDIT.\ngo 1.23\n\nuse (\n\t./api-gateway\n\t./proto\n\t./user-service\n)\n"
        );
    }

    #[test]
    fn test_apply_mixed_go_and_non_go() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let go_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&go_dir).unwrap();
        fs::write(
            go_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.22\n",
        )
        .unwrap();

        let js_dir = ws_dir.join("frontend");
        fs::create_dir_all(&js_dir).unwrap();
        fs::write(js_dir.join("package.json"), "{}").unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway", "github.com/acme/frontend"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        // Only the Go repo should appear
        assert!(content.contains("./api-gateway"));
        assert!(!content.contains("./frontend"));
    }

    #[test]
    fn test_apply_no_go_repos() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let js_dir = ws_dir.join("frontend");
        fs::create_dir_all(&js_dir).unwrap();
        fs::write(js_dir.join("package.json"), "{}").unwrap();

        let meta = make_metadata(&["github.com/acme/frontend"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        // No go.work should be written
        assert!(!ws_dir.join("go.work").exists());
    }

    #[test]
    fn test_apply_sorted_output() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        // Create repos in non-alphabetical order
        for name in &["zebra", "alpha", "middle"] {
            let d = ws_dir.join(name);
            fs::create_dir_all(&d).unwrap();
            fs::write(d.join("go.mod"), "module example.com/x\n\ngo 1.21\n").unwrap();
        }

        let meta = make_metadata(&[
            "github.com/acme/zebra",
            "github.com/acme/alpha",
            "github.com/acme/middle",
        ]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        let use_lines: Vec<&str> = content.lines().filter(|l| l.starts_with('\t')).collect();
        assert_eq!(use_lines, vec!["\t./alpha", "\t./middle", "\t./zebra"]);
    }

    #[test]
    fn test_apply_fallback_version() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let repo_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&repo_dir).unwrap();
        // go.mod without a go directive
        fs::write(repo_dir.join("go.mod"), "module example.com/api-gateway\n").unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert!(
            content.contains("go 1.21"),
            "should use fallback version 1.21"
        );
    }

    #[test]
    fn test_apply_overwrites_existing_go_work() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let repo_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&repo_dir).unwrap();
        fs::write(
            repo_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.22\n",
        )
        .unwrap();

        // Write stale go.work
        fs::write(ws_dir.join("go.work"), "stale content").unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert!(
            content.starts_with("// Code generated by wsp."),
            "go.work should be replaced, not stale"
        );
        assert!(content.contains("./api-gateway"));
    }

    #[test]
    fn test_apply_preserves_patch_version() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let api_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&api_dir).unwrap();
        fs::write(
            api_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.25.7\n",
        )
        .unwrap();

        let proto_dir = ws_dir.join("proto");
        fs::create_dir_all(&proto_dir).unwrap();
        fs::write(
            proto_dir.join("go.mod"),
            "module example.com/proto\n\ngo 1.25\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway", "github.com/acme/proto"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert!(
            content.contains("go 1.25.7"),
            "should preserve patch version: got {}",
            content
        );
    }

    #[test]
    fn test_detect_nested_go_mod() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let nested = ws_dir.join("monorepo/services/api");
        fs::create_dir_all(&nested).unwrap();
        fs::write(
            nested.join("go.mod"),
            "module example.com/monorepo/services/api\n\ngo 1.22\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/monorepo"]);
        let integration = GoIntegration;

        assert!(integration.detect(ws_dir, &meta));
    }

    #[test]
    fn test_apply_nested_go_mod() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let nested = ws_dir.join("monorepo/services/api");
        fs::create_dir_all(&nested).unwrap();
        fs::write(
            nested.join("go.mod"),
            "module example.com/monorepo/services/api\n\ngo 1.22\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/monorepo"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert!(
            content.contains("./monorepo/services/api"),
            "should include nested module path: got {}",
            content
        );
    }

    #[test]
    fn test_apply_mixed_root_and_nested() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        // Repo with root go.mod
        let root_repo = ws_dir.join("api-gateway");
        fs::create_dir_all(&root_repo).unwrap();
        fs::write(
            root_repo.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.21\n",
        )
        .unwrap();

        // Repo with nested go.mod
        let nested = ws_dir.join("monorepo/services/api");
        fs::create_dir_all(&nested).unwrap();
        fs::write(
            nested.join("go.mod"),
            "module example.com/monorepo/services/api\n\ngo 1.23\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/api-gateway", "github.com/acme/monorepo"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert!(content.contains("./api-gateway"), "root module missing");
        assert!(
            content.contains("./monorepo/services/api"),
            "nested module missing"
        );
        assert!(
            content.contains("go 1.23"),
            "should use highest version: got {}",
            content
        );
    }

    #[test]
    fn test_apply_skips_vendor() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let repo = ws_dir.join("myrepo");
        fs::create_dir_all(&repo).unwrap();
        fs::write(
            repo.join("go.mod"),
            "module example.com/myrepo\n\ngo 1.22\n",
        )
        .unwrap();

        // go.mod inside vendor/ should be ignored
        let vendor_mod = repo.join("vendor/github.com/dep");
        fs::create_dir_all(&vendor_mod).unwrap();
        fs::write(
            vendor_mod.join("go.mod"),
            "module github.com/dep\n\ngo 1.21\n",
        )
        .unwrap();

        let meta = make_metadata(&["github.com/acme/myrepo"]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        let use_lines: Vec<&str> = content.lines().filter(|l| l.starts_with('\t')).collect();
        assert_eq!(
            use_lines,
            vec!["\t./myrepo"],
            "vendor go.mod should be excluded"
        );
    }

    #[test]
    fn test_apply_includes_all_repos() {
        let tmp = tempfile::tempdir().unwrap();
        let ws_dir = tmp.path();

        let api_dir = ws_dir.join("api-gateway");
        fs::create_dir_all(&api_dir).unwrap();
        fs::write(
            api_dir.join("go.mod"),
            "module example.com/api-gateway\n\ngo 1.22\n",
        )
        .unwrap();

        let proto_dir = ws_dir.join("proto");
        fs::create_dir_all(&proto_dir).unwrap();
        fs::write(
            proto_dir.join("go.mod"),
            "module example.com/proto\n\ngo 1.23\n",
        )
        .unwrap();

        let meta = make_metadata_with_refs(&[
            ("github.com/acme/api-gateway", None),
            ("github.com/acme/proto", None),
        ]);
        let integration = GoIntegration;
        integration.apply(ws_dir, &meta).unwrap();

        let content = fs::read_to_string(ws_dir.join("go.work")).unwrap();
        assert!(content.contains("./api-gateway"));
        assert!(content.contains("./proto"));
        assert!(
            content.contains("go 1.23"),
            "should use highest version from all repos"
        );
    }
}
